from __future__ import annotations

from datetime import datetime
from typing import Protocol, runtime_checkable

from compendium.domain.models import (
    AppUser,
    AuditLog,
    Branch,
    Creator,
    Hold,
    Item,
    Loan,
    LoanPolicy,
    Patron,
    Role,
    Work,
)


@runtime_checkable
class WorkRepository(Protocol):
    def add(self, work: Work) -> Work: ...
    def get(self, id: int) -> Work | None: ...
    def get_by_isbn(self, isbn: str) -> Work | None: ...
    def list(self, limit: int = 50, offset: int = 0) -> list[Work]: ...
    def search(self, q: str, limit: int = 20) -> list[Work]: ...


@runtime_checkable
class ItemRepository(Protocol):
    def add(self, item: Item) -> Item: ...
    def get(self, id: int) -> Item | None: ...
    def get_by_barcode(self, barcode: str) -> Item | None: ...
    def update(self, item: Item) -> Item: ...
    def count_all(self) -> int: ...


@runtime_checkable
class CreatorRepository(Protocol):
    def add(self, creator: Creator) -> Creator: ...
    def get_by_sort_name(self, sort_name: str) -> Creator | None: ...


@runtime_checkable
class PatronRepository(Protocol):
    def add(self, patron: Patron) -> Patron: ...
    def get(self, id: int) -> Patron | None: ...
    def get_by_card_number(self, card_number: str) -> Patron | None: ...
    def get_by_user_id(self, user_id: int) -> Patron | None: ...
    def update(self, patron: Patron) -> Patron: ...
    def list(self, limit: int = 50, offset: int = 0) -> list[Patron]: ...


@runtime_checkable
class BranchRepository(Protocol):
    def get_default(self) -> Branch | None: ...
    def get(self, id: int) -> Branch | None: ...


@runtime_checkable
class LoanRepository(Protocol):
    def add(self, loan: Loan) -> Loan: ...
    def get(self, loan_id: int) -> Loan | None: ...
    def get_active_for_item(self, item_id: int) -> Loan | None: ...
    def get_active_for_patron(self, patron_id: int) -> list[Loan]: ...
    def update(self, loan: Loan) -> Loan: ...


@runtime_checkable
class RoleRepository(Protocol):
    def add(self, role: Role) -> Role: ...
    def get(self, role_id: int) -> Role | None: ...
    def get_by_name(self, name: str) -> Role | None: ...


@runtime_checkable
class UserRepository(Protocol):
    def add(self, user: AppUser) -> AppUser: ...
    def get(self, user_id: int) -> AppUser | None: ...
    def get_by_username(self, username: str) -> AppUser | None: ...
    def update(self, user: AppUser) -> AppUser: ...


@runtime_checkable
class HoldRepository(Protocol):
    def add(self, hold: Hold) -> Hold: ...
    def get(self, hold_id: int) -> Hold | None: ...
    def get_active_for_patron(self, patron_id: int) -> list[Hold]: ...
    def get_oldest_waiting_for_work(self, work_id: int) -> Hold | None: ...
    def get_available_for_patron_work(self, patron_id: int, work_id: int) -> Hold | None: ...
    def get_active_for_patron_work(self, patron_id: int, work_id: int) -> Hold | None: ...
    def get_expired_waiting(self, before: datetime) -> list[Hold]: ...
    def update(self, hold: Hold) -> Hold: ...


@runtime_checkable
class LoanPolicyRepository(Protocol):
    def add(self, policy: LoanPolicy) -> LoanPolicy: ...
    def get(self, policy_id: int) -> LoanPolicy | None: ...
    def get_for_media_type(self, media_type_id: int) -> LoanPolicy | None: ...
    def get_default(self) -> LoanPolicy | None: ...
    def list(self) -> list[LoanPolicy]: ...
    def update(self, policy: LoanPolicy) -> LoanPolicy: ...


@runtime_checkable
class AuditLogRepository(Protocol):
    def add(self, entry: AuditLog) -> None: ...
    def list(
        self,
        entity_type: str | None = None,
        entity_id: int | None = None,
        user_id: int | None = None,
        limit: int = 50,
    ) -> list[AuditLog]: ...
