from typing import Protocol, runtime_checkable

from compendium.domain.models import Branch, Creator, Item, Loan, Patron, Work


@runtime_checkable
class WorkRepository(Protocol):
    def add(self, work: Work) -> Work: ...
    def get(self, id: int) -> Work | None: ...
    def get_by_isbn(self, isbn: str) -> Work | None: ...
    def list(self, limit: int = 50, offset: int = 0) -> list[Work]: ...


@runtime_checkable
class ItemRepository(Protocol):
    def add(self, item: Item) -> Item: ...
    def get(self, id: int) -> Item | None: ...
    def get_by_barcode(self, barcode: str) -> Item | None: ...
    def update(self, item: Item) -> Item: ...
    def count_all(self) -> int: ...


@runtime_checkable
class CreatorRepository(Protocol):
    def add(self, creator: Creator) -> Creator: ...
    def get_by_sort_name(self, sort_name: str) -> Creator | None: ...


@runtime_checkable
class PatronRepository(Protocol):
    def add(self, patron: Patron) -> Patron: ...
    def get(self, id: int) -> Patron | None: ...
    def get_by_card_number(self, card_number: str) -> Patron | None: ...
    def list(self, limit: int = 50, offset: int = 0) -> list[Patron]: ...


@runtime_checkable
class BranchRepository(Protocol):
    def get_default(self) -> Branch | None: ...
    def get(self, id: int) -> Branch | None: ...


@runtime_checkable
class LoanRepository(Protocol):
    def add(self, loan: Loan) -> Loan: ...
    def get_active_for_item(self, item_id: int) -> Loan | None: ...
    def get_active_for_patron(self, patron_id: int) -> list[Loan]: ...
    def update(self, loan: Loan) -> Loan: ...
