from __future__ import annotations

from datetime import date, datetime
from typing import Protocol, runtime_checkable

from compendium.domain.models import (
    AppUser,
    AuditLog,
    Branch,
    ClosedDate,
    Creator,
    CuratedList,
    CuratedListEntry,
    DeletedEntity,
    Fine,
    Hold,
    Household,
    Item,
    ItemNote,
    LibraryHours,
    Loan,
    LoanPolicy,
    MediaType,
    Notification,
    Patron,
    PatronCategory,
    Role,
    Work,
)


@runtime_checkable
class MediaTypeRepository(Protocol):
    def get_by_code(self, code: str) -> MediaType | None: ...
    def list(self) -> list[MediaType]: ...


@runtime_checkable
class WorkRepository(Protocol):
    def add(self, work: Work) -> Work: ...
    def get(self, id: int) -> Work | None: ...
    def get_by_isbn(self, isbn: str) -> Work | None: ...
    def get_by_upc(self, upc: str) -> Work | None: ...
    def list(self, limit: int = 50, offset: int = 0) -> list[Work]: ...
    def search(
        self,
        q: str,
        field: str = "all",
        *,
        limit: int = 20,
        offset: int = 0,
        media_type_codes: list[str] | None = None,
        decade: int | None = None,
        available_only: bool = False,
        include_withdrawn_only: bool = False,
        order_by: str = "title",
    ) -> list[Work]: ...
    def count_search(
        self,
        q: str,
        field: str = "all",
        *,
        media_type_codes: list[str] | None = None,
        decade: int | None = None,
        available_only: bool = False,
        include_withdrawn_only: bool = False,
    ) -> int: ...
    def facet_media_counts(
        self,
        q: str,
        field: str,
        *,
        decade: int | None = None,
        available_only: bool = False,
        include_withdrawn_only: bool = False,
    ) -> list[tuple[str, str, int]]: ...
    def facet_decade_counts(
        self,
        q: str,
        field: str,
        *,
        media_type_codes: list[str] | None = None,
        available_only: bool = False,
        include_withdrawn_only: bool = False,
    ) -> list[tuple[int, int]]: ...
    def facet_available_count(
        self,
        q: str,
        field: str,
        *,
        media_type_codes: list[str] | None = None,
        decade: int | None = None,
        include_withdrawn_only: bool = False,
    ) -> int: ...
    def suggest(self, q: str, *, limit: int = 8) -> list[Work]: ...
    def list_recent(self, *, days: int, limit: int, include_withdrawn_only: bool = False) -> list[Work]: ...
    def list_recently_returned(self, *, days: int, limit: int, include_withdrawn_only: bool = False) -> list[Work]: ...
    def update(self, work: Work) -> Work: ...
    def has_loanable_item(self, work_id: int) -> bool: ...
    def first_available_loanable_copy(self, work_id: int) -> Item | None: ...
    def availability_for_works(self, work_ids: list[int]) -> dict[int, str]: ...
    def iter_for_export(
        self,
        *,
        media_type_code: str | None = None,
        branch_code: str | None = None,
        since: datetime | None = None,
    ) -> list[Work]: ...
    def iter_for_refresh(
        self,
        *,
        media_type_code: str | None = None,
        branch_code: str | None = None,
        missing_only: bool = True,
        limit: int | None = None,
    ) -> list[Work]: ...


@runtime_checkable
class ItemRepository(Protocol):
    def add(self, item: Item) -> Item: ...
    def get(self, id: int) -> Item | None: ...
    def get_by_barcode(self, barcode: str) -> Item | None: ...
    def update(self, item: Item) -> Item: ...
    def count_all(self) -> int: ...
    def list_dormant(
        self,
        *,
        not_since: datetime,
        limit: int,
        branch_id: int | None = None,
    ) -> list[tuple[Item, Work, datetime | None]]: ...


@runtime_checkable
class CreatorRepository(Protocol):
    def add(self, creator: Creator) -> Creator: ...
    def get(self, id: int) -> Creator | None: ...
    def get_by_sort_name(self, sort_name: str) -> Creator | None: ...
    def update(self, creator: Creator) -> Creator: ...
    def list_works(self, creator_id: int, *, include_withdrawn_only: bool = False) -> list[Work]: ...


@runtime_checkable
class PatronRepository(Protocol):
    def add(self, patron: Patron) -> Patron: ...
    def get(self, id: int) -> Patron | None: ...
    def get_by_card_number(self, card_number: str) -> Patron | None: ...
    def get_by_user_id(self, user_id: int) -> Patron | None: ...
    def update(self, patron: Patron) -> Patron: ...
    def list(self, limit: int = 50, offset: int = 0, include_inactive: bool = False) -> list[Patron]: ...
    def list_by_household(self, household_id: int) -> list[Patron]: ...


@runtime_checkable
class BranchRepository(Protocol):
    def get_default(self) -> Branch | None: ...
    def get(self, id: int) -> Branch | None: ...
    def get_by_code(self, code: str) -> Branch | None: ...
    def list(self) -> list[Branch]: ...
    def update(self, branch: Branch) -> Branch: ...


@runtime_checkable
class LoanRepository(Protocol):
    def add(self, loan: Loan) -> Loan: ...
    def get(self, loan_id: int) -> Loan | None: ...
    def get_active_for_item(self, item_id: int) -> Loan | None: ...
    def get_active_for_patron(self, patron_id: int) -> list[Loan]: ...
    def get_most_recent_for_item(self, item_id: int) -> Loan | None: ...
    def list_active_overdue(self, *, patron_id: int | None = None) -> list[Loan]: ...
    def list_due_within(self, *, days: int) -> list[Loan]: ...
    def update(self, loan: Loan) -> Loan: ...
    def count_checkouts_by_month(
        self, *, since: datetime, branch_id: int | None = None
    ) -> list[tuple[int, int, int]]: ...
    def popular_works(
        self,
        *,
        since: datetime,
        until: datetime,
        limit: int,
        branch_id: int | None = None,
    ) -> list[tuple[int, int]]: ...
    def list_active_overdue_joined(
        self, *, branch_id: int | None = None
    ) -> list[tuple[Loan, Patron, Item, Work]]: ...
    def list_active(
        self,
        *,
        due: str | None = None,
        branch_id: int | None = None,
        query: str | None = None,
        limit: int = 50,
        offset: int = 0,
    ) -> list[Loan]: ...
    def count_active(
        self,
        *,
        due: str | None = None,
        branch_id: int | None = None,
        query: str | None = None,
    ) -> int: ...
    def list_for_patron(
        self,
        patron_id: int,
        *,
        status: str = "active",
        limit: int = 100,
        offset: int = 0,
    ) -> list[Loan]: ...
    def count_for_patron(self, patron_id: int, *, status: str = "active") -> int: ...
    def list_for_item(
        self, item_id: int, *, limit: int = 25, offset: int = 0
    ) -> list[Loan]: ...


@runtime_checkable
class RoleRepository(Protocol):
    def add(self, role: Role) -> Role: ...
    def get(self, role_id: int) -> Role | None: ...
    def get_by_name(self, name: str) -> Role | None: ...
    def list(self) -> list[Role]: ...
    def update(self, role: Role) -> Role: ...


@runtime_checkable
class UserRepository(Protocol):
    def add(self, user: AppUser) -> AppUser: ...
    def get(self, user_id: int) -> AppUser | None: ...
    def get_by_username(self, username: str) -> AppUser | None: ...
    def update(self, user: AppUser) -> AppUser: ...
    def list(self, limit: int = 50, offset: int = 0, include_inactive: bool = False) -> list[AppUser]: ...


@runtime_checkable
class HoldRepository(Protocol):
    def add(self, hold: Hold) -> Hold: ...
    def get(self, hold_id: int) -> Hold | None: ...
    def get_active_for_patron(self, patron_id: int) -> list[Hold]: ...
    def get_active_for_work(self, work_id: int) -> list[Hold]: ...
    def get_oldest_waiting_for_work(self, work_id: int) -> Hold | None: ...
    def get_available_for_patron_work(self, patron_id: int, work_id: int) -> Hold | None: ...
    def get_active_for_patron_work(self, patron_id: int, work_id: int) -> Hold | None: ...
    def get_expired_waiting(self, before: datetime) -> list[Hold]: ...
    def list_suspended_expiring_on_or_before(self, cutoff: date) -> list[Hold]: ...
    def list_active(
        self,
        *,
        status: str | None = None,
        branch_id: int | None = None,
        work_id: int | None = None,
        patron_id: int | None = None,
        query: str | None = None,
        older_than_days: int | None = None,
        limit: int = 50,
        offset: int = 0,
    ) -> list[Hold]: ...
    def count_active(
        self,
        *,
        status: str | None = None,
        branch_id: int | None = None,
        work_id: int | None = None,
        patron_id: int | None = None,
        query: str | None = None,
        older_than_days: int | None = None,
    ) -> int: ...
    def queue_for_work(self, work_id: int) -> list[Hold]: ...
    def queue_position(self, hold_id: int) -> int | None: ...
    def update(self, hold: Hold) -> Hold: ...


@runtime_checkable
class LoanPolicyRepository(Protocol):
    def add(self, policy: LoanPolicy) -> LoanPolicy: ...
    def get(self, policy_id: int) -> LoanPolicy | None: ...
    def get_for_media_type(self, media_type_id: int) -> LoanPolicy | None: ...
    def get_default(self) -> LoanPolicy | None: ...
    def resolve(
        self, media_type_id: int | None, patron_category_id: int | None
    ) -> LoanPolicy | None: ...
    def list(self) -> list[LoanPolicy]: ...
    def update(self, policy: LoanPolicy) -> LoanPolicy: ...
    def clear_defaults(self) -> None: ...


@runtime_checkable
class PatronCategoryRepository(Protocol):
    def add(self, category: PatronCategory) -> PatronCategory: ...
    def get(self, category_id: int) -> PatronCategory | None: ...
    def get_by_code(self, code: str) -> PatronCategory | None: ...
    def get_default(self) -> PatronCategory | None: ...
    def list(self) -> list[PatronCategory]: ...
    def update(self, category: PatronCategory) -> PatronCategory: ...
    def delete(self, category: PatronCategory) -> None: ...
    def clear_defaults(self) -> None: ...
    def count_patrons_in(self, category_id: int) -> int: ...
    def count_policies_in(self, category_id: int) -> int: ...


@runtime_checkable
class FineRepository(Protocol):
    def add(self, fine: Fine) -> Fine: ...
    def get(self, fine_id: int) -> Fine | None: ...
    def list(
        self,
        *,
        patron_id: int | None = None,
        status: str | None = None,
        limit: int = 50,
    ) -> list[Fine]: ...
    def get_outstanding_overdue_for_loan(self, loan_id: int) -> Fine | None: ...
    def outstanding_total(self, patron_id: int) -> int: ...
    def list_outstanding(
        self,
        *,
        kind: str | None = None,
        query: str | None = None,
        limit: int = 50,
        offset: int = 0,
    ) -> list[Fine]: ...
    def count_outstanding(
        self, *, kind: str | None = None, query: str | None = None
    ) -> int: ...
    def outstanding_total_all(
        self, *, kind: str | None = None, query: str | None = None
    ) -> int: ...
    def update(self, fine: Fine) -> Fine: ...


@runtime_checkable
class NotificationRepository(Protocol):
    def add(self, notification: Notification) -> Notification: ...
    def get(self, notification_id: int) -> Notification | None: ...
    def list(
        self,
        *,
        status: str | None = None,
        template_key: str | None = None,
        limit: int = 50,
        offset: int = 0,
    ) -> list[Notification]: ...
    def list_pending(self, *, limit: int) -> list[Notification]: ...
    def get_existing(
        self,
        *,
        loan_id: int | None,
        hold_id: int | None,
        template_key: str,
        discriminator: int,
    ) -> Notification | None: ...
    def update(self, notification: Notification) -> Notification: ...
    def prune(
        self,
        *,
        older_than: datetime | None = None,
        status: str | None = None,
        dry_run: bool = False,
    ) -> int: ...


@runtime_checkable
class AuditLogRepository(Protocol):
    def add(self, entry: AuditLog) -> None: ...
    def list(
        self,
        entity_type: str | None = None,
        entity_id: int | None = None,
        user_id: int | None = None,
        limit: int = 50,
    ) -> list[AuditLog]: ...
    def count_older_than(self, cutoff: datetime) -> int: ...
    def delete_older_than(self, cutoff: datetime) -> int: ...


@runtime_checkable
class CounterRepository(Protocol):
    def next(self, key: str) -> int: ...


@runtime_checkable
class LibraryHoursRepository(Protocol):
    def list(self) -> list[LibraryHours]: ...
    def get(self, weekday: int) -> LibraryHours | None: ...
    def update(self, hours: LibraryHours) -> LibraryHours: ...


@runtime_checkable
class ClosedDateRepository(Protocol):
    def list_in_range(self, start: date, end: date) -> list[ClosedDate]: ...
    def get(self, closed_date_id: int) -> ClosedDate | None: ...
    def add(self, closed_date: ClosedDate) -> ClosedDate: ...
    def update(self, closed_date: ClosedDate) -> ClosedDate: ...
    def delete(self, closed_date: ClosedDate) -> None: ...
    def list(self, *, limit: int = 100, offset: int = 0) -> list[ClosedDate]: ...


@runtime_checkable
class HouseholdRepository(Protocol):
    def add(self, household: Household) -> Household: ...
    def get(self, household_id: int) -> Household | None: ...
    def list(self, *, limit: int = 50, offset: int = 0) -> list[Household]: ...
    def count(self) -> int: ...
    def update(self, household: Household) -> Household: ...
    def delete(self, household: Household) -> None: ...


@runtime_checkable
class ItemNoteRepository(Protocol):
    def add(self, note: ItemNote) -> ItemNote: ...
    def get(self, note_id: int) -> ItemNote | None: ...
    def list_for_item(self, item_id: int) -> list[ItemNote]: ...
    def delete(self, note: ItemNote) -> None: ...


@runtime_checkable
class CuratedListRepository(Protocol):
    def add(self, list: CuratedList) -> CuratedList: ...
    def get(self, list_id: int) -> CuratedList | None: ...
    def get_by_slug(self, slug: str) -> CuratedList | None: ...
    def slug_exists(self, slug: str) -> bool: ...
    def list(self, *, limit: int, offset: int, public_only: bool, featured_only: bool) -> list[CuratedList]: ...
    def count(self, *, public_only: bool, featured_only: bool) -> int: ...
    def update(self, list: CuratedList) -> CuratedList: ...
    def delete(self, list: CuratedList) -> None: ...
    def add_entry(self, entry: CuratedListEntry) -> CuratedListEntry: ...
    def remove_entry(self, list_id: int, work_id: int) -> None: ...
    def get_entry(self, list_id: int, work_id: int) -> CuratedListEntry | None: ...
    def update_entry(self, entry: CuratedListEntry) -> CuratedListEntry: ...
    def max_entry_order(self, list_id: int) -> int: ...


@runtime_checkable
class TrashRepository(Protocol):
    def add(self, entity: DeletedEntity) -> DeletedEntity: ...
    def get(self, trash_id: int) -> DeletedEntity | None: ...
    def list(self, *, entity_type: str, limit: int = 50) -> list[DeletedEntity]: ...
    def delete(self, entity: DeletedEntity) -> None: ...
    def delete_older_than(self, entity_type: str, cutoff: datetime) -> int: ...
    def count_active_loans(self, work_id: int) -> int: ...
    def count_outstanding_fines(self, work_id: int) -> int: ...
    def snapshot_work_graph(self, work: Work) -> dict: ...          # Task 3
    def delete_work_graph(self, work: Work) -> None: ...            # Task 3
    def find_restore_collisions(self, payload: dict) -> list[str]: ...  # Task 4
    def restore_work_graph(self, payload: dict) -> Work: ...        # Task 4
