"""add_holds_and_loan_policies

Revision ID: a9b9ea15933f
Revises: 6e72f68cf15a
Create Date: 2026-04-18 00:40:34.919677

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a9b9ea15933f'
down_revision: Union[str, Sequence[str], None] = '6e72f68cf15a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('loan_policy',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('media_type_id', sa.Integer(), nullable=True),
    sa.Column('loan_period_days', sa.Integer(), nullable=False),
    sa.Column('max_renewals', sa.Integer(), server_default='2', nullable=False),
    sa.Column('is_default', sa.Boolean(), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['media_type_id'], ['media_type.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hold',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('work_id', sa.Integer(), nullable=False),
    sa.Column('patron_id', sa.Integer(), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('placed_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notified_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['branch.id'], ),
    sa.ForeignKeyConstraint(['patron_id'], ['patron.id'], ),
    sa.ForeignKeyConstraint(['work_id'], ['work.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('hold', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_hold_patron_id'), ['patron_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_hold_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_hold_work_id'), ['work_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hold', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_hold_work_id'))
        batch_op.drop_index(batch_op.f('ix_hold_status'))
        batch_op.drop_index(batch_op.f('ix_hold_patron_id'))

    op.drop_table('hold')
    op.drop_table('loan_policy')
    # ### end Alembic commands ###
