"""initial schema

Revision ID: cec97d4626cf
Revises: 
Create Date: 2026-04-17 22:46:52.741503

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cec97d4626cf'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('branch',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('address', sa.JSON(), nullable=True),
    sa.Column('is_default', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('creator',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('display_name', sa.String(length=256), nullable=False),
    sa.Column('sort_name', sa.String(length=256), nullable=False),
    sa.Column('external_ids', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('creator', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_creator_sort_name'), ['sort_name'], unique=False)

    op.create_table('media_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('display_name', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('patron',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('library_card_number', sa.String(length=64), nullable=False),
    sa.Column('full_name', sa.String(length=256), nullable=False),
    sa.Column('contact_email', sa.String(length=256), nullable=True),
    sa.Column('contact_phone', sa.String(length=64), nullable=True),
    sa.Column('address', sa.JSON(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('library_card_number')
    )
    op.create_table('work',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('subtitle', sa.String(length=512), nullable=True),
    sa.Column('media_type_id', sa.Integer(), nullable=False),
    sa.Column('publisher', sa.String(length=256), nullable=True),
    sa.Column('publication_year', sa.Integer(), nullable=True),
    sa.Column('edition', sa.String(length=128), nullable=True),
    sa.Column('language', sa.String(length=8), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('isbn', sa.String(length=13), nullable=True),
    sa.Column('upc', sa.String(length=20), nullable=True),
    sa.Column('classification_scheme', sa.String(length=32), nullable=True),
    sa.Column('classification_code', sa.String(length=64), nullable=True),
    sa.Column('cover_image_url', sa.String(length=512), nullable=True),
    sa.Column('extra_metadata', sa.JSON(), nullable=False),
    sa.Column('external_ids', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['media_type_id'], ['media_type.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('work', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_work_isbn'), ['isbn'], unique=False)
        batch_op.create_index(batch_op.f('ix_work_upc'), ['upc'], unique=False)

    op.create_table('item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('work_id', sa.Integer(), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=False),
    sa.Column('barcode', sa.String(length=64), nullable=False),
    sa.Column('accession_number', sa.String(length=64), nullable=False),
    sa.Column('call_number', sa.String(length=64), nullable=True),
    sa.Column('location', sa.String(length=256), nullable=True),
    sa.Column('condition', sa.String(length=16), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('acquired_at', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['branch.id'], ),
    sa.ForeignKeyConstraint(['work_id'], ['work.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('accession_number'),
    sa.UniqueConstraint('barcode')
    )
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_item_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_item_work_id'), ['work_id'], unique=False)

    op.create_table('work_creator',
    sa.Column('work_id', sa.Integer(), nullable=False),
    sa.Column('creator_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['creator_id'], ['creator.id'], ),
    sa.ForeignKeyConstraint(['work_id'], ['work.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('work_id', 'creator_id', 'role')
    )
    op.create_table('loan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('patron_id', sa.Integer(), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=False),
    sa.Column('checked_out_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('returned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('renewal_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['branch.id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['item.id'], ),
    sa.ForeignKeyConstraint(['patron_id'], ['patron.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('loan', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_loan_item_id'), ['item_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_loan_patron_id'), ['patron_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_loan_returned_at'), ['returned_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('loan', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_loan_returned_at'))
        batch_op.drop_index(batch_op.f('ix_loan_patron_id'))
        batch_op.drop_index(batch_op.f('ix_loan_item_id'))

    op.drop_table('loan')
    op.drop_table('work_creator')
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_item_work_id'))
        batch_op.drop_index(batch_op.f('ix_item_status'))

    op.drop_table('item')
    with op.batch_alter_table('work', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_work_upc'))
        batch_op.drop_index(batch_op.f('ix_work_isbn'))

    op.drop_table('work')
    op.drop_table('patron')
    op.drop_table('media_type')
    with op.batch_alter_table('creator', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_creator_sort_name'))

    op.drop_table('creator')
    op.drop_table('branch')
    # ### end Alembic commands ###
