#!/usr/bin/env python3
"""Generate ``src/compendium/web/tz_regions.py`` from the IANA tz tables.

The settings timezone picker groups zones **by country** (a Region select of
country names, a City select of that country's zones). The authoritative,
user-facing geographic zone list is the IANA ``zone.tab`` (or ``zone1970.tab``)
plus ``iso3166.tab`` for country names — the same data desktop OS pickers use.
It excludes the ~45 legacy aliases (``US/Eastern``, ``GB``, ``Brazil/East`` …)
that ``zoneinfo.available_timezones()`` would otherwise dump into the list.

We read those tables at *generation* time and emit a plain Python module so the
running app has no dependency on the tz tab files (which a slim container or
Windows host may not ship). Re-run after a tzdata bump:

    uv run python scripts/gen_tz_regions.py

It rewrites the committed module in place. Review the diff before committing.
"""

from __future__ import annotations

from pathlib import Path

# Anglophone-priority countries shown first (this is an English-language app
# whose users are overwhelmingly in these locales), with UTC pinned at the very
# top as the default. Everything else follows alphabetically by display name.
_PRIORITY_CC = ["US", "CA", "GB", "IE", "AU", "NZ"]

# iso3166.tab names are terse/awkward for a few of our priority locales.
_NAME_OVERRIDES = {"GB": "United Kingdom"}

_ZONEINFO_DIRS = ["/usr/share/zoneinfo", "/etc/zoneinfo"]


def _find(name: str) -> Path:
    for d in _ZONEINFO_DIRS:
        p = Path(d) / name
        if p.exists():
            return p
    raise SystemExit(f"could not locate {name} under {_ZONEINFO_DIRS}")


def _load_country_names() -> dict[str, str]:
    names: dict[str, str] = {}
    for line in _find("iso3166.tab").read_text().splitlines():
        if line.startswith("#") or not line.strip():
            continue
        code, name = line.split("\t", 1)
        names[code] = _NAME_OVERRIDES.get(code, name.strip())
    return names


def _load_zones_by_cc() -> dict[str, list[str]]:
    # Prefer zone1970.tab (multi-country rows) when present, else zone.tab.
    try:
        tab = _find("zone1970.tab")
        multi = True
    except SystemExit:
        tab = _find("zone.tab")
        multi = False
    by_cc: dict[str, list[str]] = {}
    for line in tab.read_text().splitlines():
        if line.startswith("#") or not line.strip():
            continue
        parts = line.split("\t")
        codes = parts[0].split(",") if multi else [parts[0]]
        tz = parts[2]
        # Attribute the zone to its first listed country only — avoids the same
        # zone appearing under several countries (e.g. shared European zones).
        by_cc.setdefault(codes[0], []).append(tz)
    return by_cc


def _city_label(zone: str) -> str:
    return zone.rsplit("/", 1)[-1].replace("_", " ")


def _build() -> list[tuple[str, list[tuple[str, str]]]]:
    names = _load_country_names()
    by_cc = _load_zones_by_cc()

    def group_for(cc: str) -> tuple[str, list[tuple[str, str]]]:
        zones = sorted(by_cc[cc], key=_city_label)
        return (names.get(cc, cc), [(z, _city_label(z)) for z in zones])

    groups: list[tuple[str, list[tuple[str, str]]]] = [("UTC", [("UTC", "UTC")])]
    for cc in _PRIORITY_CC:
        if cc in by_cc:
            groups.append(group_for(cc))
    # Visual separator between the pinned locales and the full A–Z list.
    groups.append(("──────────", []))

    rest_cc = [cc for cc in by_cc if cc not in _PRIORITY_CC]
    for cc in sorted(rest_cc, key=lambda c: names.get(c, c).lower()):
        groups.append(group_for(cc))
    return groups


def _render(groups: list[tuple[str, list[tuple[str, str]]]]) -> str:
    lines = [
        '"""IANA timezones grouped by country for the settings timezone picker.',
        "",
        "AUTO-GENERATED by scripts/gen_tz_regions.py — do not edit by hand.",
        "Regenerate after a tzdata bump:  uv run python scripts/gen_tz_regions.py",
        "",
        "Each entry is ``(region_label, [(iana_zone, city_label), ...])``. UTC and the",
        "anglophone-priority countries are pinned first; an empty-zone entry is a",
        "visual separator. Canonical zones only (legacy aliases are intentionally",
        "excluded); a stored value outside this list is re-injected at render time.",
        '"""',
        "",
        "from __future__ import annotations",
        "",
        "TZ_REGIONS: list[tuple[str, list[tuple[str, str]]]] = [",
    ]
    for label, zones in groups:
        if not zones:
            lines.append(f"    ({label!r}, []),")
            continue
        lines.append(f"    ({label!r}, [")
        for zone, city in zones:
            lines.append(f"        ({zone!r}, {city!r}),")
        lines.append("    ]),")
    lines.append("]")
    lines.append("")
    return "\n".join(lines)


def main() -> None:
    out = Path(__file__).resolve().parent.parent / "src" / "compendium" / "web" / "tz_regions.py"
    groups = _build()
    out.write_text(_render(groups))
    n_zones = sum(len(z) for _, z in groups)
    print(f"wrote {out} — {len(groups)} groups, {n_zones} zones")


if __name__ == "__main__":
    main()
