"""IANA timezones grouped by country for the settings timezone picker.

AUTO-GENERATED by scripts/gen_tz_regions.py — do not edit by hand.
Regenerate after a tzdata bump:  uv run python scripts/gen_tz_regions.py

Each entry is ``(region_label, [(iana_zone, city_label), ...])``. UTC and the
anglophone-priority countries are pinned first; an empty-zone entry is a
visual separator. Canonical zones only (legacy aliases are intentionally
excluded); a stored value outside this list is re-injected at render time.
"""

from __future__ import annotations

TZ_REGIONS: list[tuple[str, list[tuple[str, str]]]] = [
    ('UTC', [
        ('UTC', 'UTC'),
    ]),
    ('United States', [
        ('America/Adak', 'Adak'),
        ('America/Anchorage', 'Anchorage'),
        ('America/North_Dakota/Beulah', 'Beulah'),
        ('America/Boise', 'Boise'),
        ('America/North_Dakota/Center', 'Center'),
        ('America/Chicago', 'Chicago'),
        ('America/Denver', 'Denver'),
        ('America/Detroit', 'Detroit'),
        ('Pacific/Honolulu', 'Honolulu'),
        ('America/Indiana/Indianapolis', 'Indianapolis'),
        ('America/Juneau', 'Juneau'),
        ('America/Indiana/Knox', 'Knox'),
        ('America/Los_Angeles', 'Los Angeles'),
        ('America/Kentucky/Louisville', 'Louisville'),
        ('America/Indiana/Marengo', 'Marengo'),
        ('America/Menominee', 'Menominee'),
        ('America/Metlakatla', 'Metlakatla'),
        ('America/Kentucky/Monticello', 'Monticello'),
        ('America/North_Dakota/New_Salem', 'New Salem'),
        ('America/New_York', 'New York'),
        ('America/Nome', 'Nome'),
        ('America/Indiana/Petersburg', 'Petersburg'),
        ('America/Phoenix', 'Phoenix'),
        ('America/Sitka', 'Sitka'),
        ('America/Indiana/Tell_City', 'Tell City'),
        ('America/Indiana/Vevay', 'Vevay'),
        ('America/Indiana/Vincennes', 'Vincennes'),
        ('America/Indiana/Winamac', 'Winamac'),
        ('America/Yakutat', 'Yakutat'),
    ]),
    ('Canada', [
        ('America/Atikokan', 'Atikokan'),
        ('America/Blanc-Sablon', 'Blanc-Sablon'),
        ('America/Cambridge_Bay', 'Cambridge Bay'),
        ('America/Creston', 'Creston'),
        ('America/Dawson', 'Dawson'),
        ('America/Dawson_Creek', 'Dawson Creek'),
        ('America/Edmonton', 'Edmonton'),
        ('America/Fort_Nelson', 'Fort Nelson'),
        ('America/Glace_Bay', 'Glace Bay'),
        ('America/Goose_Bay', 'Goose Bay'),
        ('America/Halifax', 'Halifax'),
        ('America/Inuvik', 'Inuvik'),
        ('America/Iqaluit', 'Iqaluit'),
        ('America/Moncton', 'Moncton'),
        ('America/Rankin_Inlet', 'Rankin Inlet'),
        ('America/Regina', 'Regina'),
        ('America/Resolute', 'Resolute'),
        ('America/St_Johns', 'St Johns'),
        ('America/Swift_Current', 'Swift Current'),
        ('America/Toronto', 'Toronto'),
        ('America/Vancouver', 'Vancouver'),
        ('America/Whitehorse', 'Whitehorse'),
        ('America/Winnipeg', 'Winnipeg'),
    ]),
    ('United Kingdom', [
        ('Europe/London', 'London'),
    ]),
    ('Ireland', [
        ('Europe/Dublin', 'Dublin'),
    ]),
    ('Australia', [
        ('Australia/Adelaide', 'Adelaide'),
        ('Australia/Brisbane', 'Brisbane'),
        ('Australia/Broken_Hill', 'Broken Hill'),
        ('Australia/Darwin', 'Darwin'),
        ('Australia/Eucla', 'Eucla'),
        ('Australia/Hobart', 'Hobart'),
        ('Australia/Lindeman', 'Lindeman'),
        ('Australia/Lord_Howe', 'Lord Howe'),
        ('Antarctica/Macquarie', 'Macquarie'),
        ('Australia/Melbourne', 'Melbourne'),
        ('Australia/Perth', 'Perth'),
        ('Australia/Sydney', 'Sydney'),
    ]),
    ('New Zealand', [
        ('Pacific/Auckland', 'Auckland'),
        ('Pacific/Chatham', 'Chatham'),
    ]),
    ('──────────', []),
    ('Afghanistan', [
        ('Asia/Kabul', 'Kabul'),
    ]),
    ('Albania', [
        ('Europe/Tirane', 'Tirane'),
    ]),
    ('Algeria', [
        ('Africa/Algiers', 'Algiers'),
    ]),
    ('Andorra', [
        ('Europe/Andorra', 'Andorra'),
    ]),
    ('Angola', [
        ('Africa/Luanda', 'Luanda'),
    ]),
    ('Anguilla', [
        ('America/Anguilla', 'Anguilla'),
    ]),
    ('Antarctica', [
        ('Antarctica/Casey', 'Casey'),
        ('Antarctica/Davis', 'Davis'),
        ('Antarctica/DumontDUrville', 'DumontDUrville'),
        ('Antarctica/Mawson', 'Mawson'),
        ('Antarctica/McMurdo', 'McMurdo'),
        ('Antarctica/Palmer', 'Palmer'),
        ('Antarctica/Rothera', 'Rothera'),
        ('Antarctica/Syowa', 'Syowa'),
        ('Antarctica/Troll', 'Troll'),
        ('Antarctica/Vostok', 'Vostok'),
    ]),
    ('Antigua & Barbuda', [
        ('America/Antigua', 'Antigua'),
    ]),
    ('Argentina', [
        ('America/Argentina/Buenos_Aires', 'Buenos Aires'),
        ('America/Argentina/Catamarca', 'Catamarca'),
        ('America/Argentina/Cordoba', 'Cordoba'),
        ('America/Argentina/Jujuy', 'Jujuy'),
        ('America/Argentina/La_Rioja', 'La Rioja'),
        ('America/Argentina/Mendoza', 'Mendoza'),
        ('America/Argentina/Rio_Gallegos', 'Rio Gallegos'),
        ('America/Argentina/Salta', 'Salta'),
        ('America/Argentina/San_Juan', 'San Juan'),
        ('America/Argentina/San_Luis', 'San Luis'),
        ('America/Argentina/Tucuman', 'Tucuman'),
        ('America/Argentina/Ushuaia', 'Ushuaia'),
    ]),
    ('Armenia', [
        ('Asia/Yerevan', 'Yerevan'),
    ]),
    ('Aruba', [
        ('America/Aruba', 'Aruba'),
    ]),
    ('Austria', [
        ('Europe/Vienna', 'Vienna'),
    ]),
    ('Azerbaijan', [
        ('Asia/Baku', 'Baku'),
    ]),
    ('Bahamas', [
        ('America/Nassau', 'Nassau'),
    ]),
    ('Bahrain', [
        ('Asia/Bahrain', 'Bahrain'),
    ]),
    ('Bangladesh', [
        ('Asia/Dhaka', 'Dhaka'),
    ]),
    ('Barbados', [
        ('America/Barbados', 'Barbados'),
    ]),
    ('Belarus', [
        ('Europe/Minsk', 'Minsk'),
    ]),
    ('Belgium', [
        ('Europe/Brussels', 'Brussels'),
    ]),
    ('Belize', [
        ('America/Belize', 'Belize'),
    ]),
    ('Benin', [
        ('Africa/Porto-Novo', 'Porto-Novo'),
    ]),
    ('Bermuda', [
        ('Atlantic/Bermuda', 'Bermuda'),
    ]),
    ('Bhutan', [
        ('Asia/Thimphu', 'Thimphu'),
    ]),
    ('Bolivia', [
        ('America/La_Paz', 'La Paz'),
    ]),
    ('Bosnia & Herzegovina', [
        ('Europe/Sarajevo', 'Sarajevo'),
    ]),
    ('Botswana', [
        ('Africa/Gaborone', 'Gaborone'),
    ]),
    ('Brazil', [
        ('America/Araguaina', 'Araguaina'),
        ('America/Bahia', 'Bahia'),
        ('America/Belem', 'Belem'),
        ('America/Boa_Vista', 'Boa Vista'),
        ('America/Campo_Grande', 'Campo Grande'),
        ('America/Cuiaba', 'Cuiaba'),
        ('America/Eirunepe', 'Eirunepe'),
        ('America/Fortaleza', 'Fortaleza'),
        ('America/Maceio', 'Maceio'),
        ('America/Manaus', 'Manaus'),
        ('America/Noronha', 'Noronha'),
        ('America/Porto_Velho', 'Porto Velho'),
        ('America/Recife', 'Recife'),
        ('America/Rio_Branco', 'Rio Branco'),
        ('America/Santarem', 'Santarem'),
        ('America/Sao_Paulo', 'Sao Paulo'),
    ]),
    ('British Indian Ocean Territory', [
        ('Indian/Chagos', 'Chagos'),
    ]),
    ('Brunei', [
        ('Asia/Brunei', 'Brunei'),
    ]),
    ('Bulgaria', [
        ('Europe/Sofia', 'Sofia'),
    ]),
    ('Burkina Faso', [
        ('Africa/Ouagadougou', 'Ouagadougou'),
    ]),
    ('Burundi', [
        ('Africa/Bujumbura', 'Bujumbura'),
    ]),
    ('Cambodia', [
        ('Asia/Phnom_Penh', 'Phnom Penh'),
    ]),
    ('Cameroon', [
        ('Africa/Douala', 'Douala'),
    ]),
    ('Cape Verde', [
        ('Atlantic/Cape_Verde', 'Cape Verde'),
    ]),
    ('Caribbean NL', [
        ('America/Kralendijk', 'Kralendijk'),
    ]),
    ('Cayman Islands', [
        ('America/Cayman', 'Cayman'),
    ]),
    ('Central African Rep.', [
        ('Africa/Bangui', 'Bangui'),
    ]),
    ('Chad', [
        ('Africa/Ndjamena', 'Ndjamena'),
    ]),
    ('Chile', [
        ('America/Coyhaique', 'Coyhaique'),
        ('Pacific/Easter', 'Easter'),
        ('America/Punta_Arenas', 'Punta Arenas'),
        ('America/Santiago', 'Santiago'),
    ]),
    ('China', [
        ('Asia/Shanghai', 'Shanghai'),
        ('Asia/Urumqi', 'Urumqi'),
    ]),
    ('Christmas Island', [
        ('Indian/Christmas', 'Christmas'),
    ]),
    ('Cocos (Keeling) Islands', [
        ('Indian/Cocos', 'Cocos'),
    ]),
    ('Colombia', [
        ('America/Bogota', 'Bogota'),
    ]),
    ('Comoros', [
        ('Indian/Comoro', 'Comoro'),
    ]),
    ('Congo (Dem. Rep.)', [
        ('Africa/Kinshasa', 'Kinshasa'),
        ('Africa/Lubumbashi', 'Lubumbashi'),
    ]),
    ('Congo (Rep.)', [
        ('Africa/Brazzaville', 'Brazzaville'),
    ]),
    ('Cook Islands', [
        ('Pacific/Rarotonga', 'Rarotonga'),
    ]),
    ('Costa Rica', [
        ('America/Costa_Rica', 'Costa Rica'),
    ]),
    ('Croatia', [
        ('Europe/Zagreb', 'Zagreb'),
    ]),
    ('Cuba', [
        ('America/Havana', 'Havana'),
    ]),
    ('Curaçao', [
        ('America/Curacao', 'Curacao'),
    ]),
    ('Cyprus', [
        ('Asia/Famagusta', 'Famagusta'),
        ('Asia/Nicosia', 'Nicosia'),
    ]),
    ('Czech Republic', [
        ('Europe/Prague', 'Prague'),
    ]),
    ("Côte d'Ivoire", [
        ('Africa/Abidjan', 'Abidjan'),
    ]),
    ('Denmark', [
        ('Europe/Copenhagen', 'Copenhagen'),
    ]),
    ('Djibouti', [
        ('Africa/Djibouti', 'Djibouti'),
    ]),
    ('Dominica', [
        ('America/Dominica', 'Dominica'),
    ]),
    ('Dominican Republic', [
        ('America/Santo_Domingo', 'Santo Domingo'),
    ]),
    ('East Timor', [
        ('Asia/Dili', 'Dili'),
    ]),
    ('Ecuador', [
        ('Pacific/Galapagos', 'Galapagos'),
        ('America/Guayaquil', 'Guayaquil'),
    ]),
    ('Egypt', [
        ('Africa/Cairo', 'Cairo'),
    ]),
    ('El Salvador', [
        ('America/El_Salvador', 'El Salvador'),
    ]),
    ('Equatorial Guinea', [
        ('Africa/Malabo', 'Malabo'),
    ]),
    ('Eritrea', [
        ('Africa/Asmara', 'Asmara'),
    ]),
    ('Estonia', [
        ('Europe/Tallinn', 'Tallinn'),
    ]),
    ('Eswatini (Swaziland)', [
        ('Africa/Mbabane', 'Mbabane'),
    ]),
    ('Ethiopia', [
        ('Africa/Addis_Ababa', 'Addis Ababa'),
    ]),
    ('Falkland Islands', [
        ('Atlantic/Stanley', 'Stanley'),
    ]),
    ('Faroe Islands', [
        ('Atlantic/Faroe', 'Faroe'),
    ]),
    ('Fiji', [
        ('Pacific/Fiji', 'Fiji'),
    ]),
    ('Finland', [
        ('Europe/Helsinki', 'Helsinki'),
    ]),
    ('France', [
        ('Europe/Paris', 'Paris'),
    ]),
    ('French Guiana', [
        ('America/Cayenne', 'Cayenne'),
    ]),
    ('French Polynesia', [
        ('Pacific/Gambier', 'Gambier'),
        ('Pacific/Marquesas', 'Marquesas'),
        ('Pacific/Tahiti', 'Tahiti'),
    ]),
    ('French S. Terr.', [
        ('Indian/Kerguelen', 'Kerguelen'),
    ]),
    ('Gabon', [
        ('Africa/Libreville', 'Libreville'),
    ]),
    ('Gambia', [
        ('Africa/Banjul', 'Banjul'),
    ]),
    ('Georgia', [
        ('Asia/Tbilisi', 'Tbilisi'),
    ]),
    ('Germany', [
        ('Europe/Berlin', 'Berlin'),
        ('Europe/Busingen', 'Busingen'),
    ]),
    ('Ghana', [
        ('Africa/Accra', 'Accra'),
    ]),
    ('Gibraltar', [
        ('Europe/Gibraltar', 'Gibraltar'),
    ]),
    ('Greece', [
        ('Europe/Athens', 'Athens'),
    ]),
    ('Greenland', [
        ('America/Danmarkshavn', 'Danmarkshavn'),
        ('America/Nuuk', 'Nuuk'),
        ('America/Scoresbysund', 'Scoresbysund'),
        ('America/Thule', 'Thule'),
    ]),
    ('Grenada', [
        ('America/Grenada', 'Grenada'),
    ]),
    ('Guadeloupe', [
        ('America/Guadeloupe', 'Guadeloupe'),
    ]),
    ('Guam', [
        ('Pacific/Guam', 'Guam'),
    ]),
    ('Guatemala', [
        ('America/Guatemala', 'Guatemala'),
    ]),
    ('Guernsey', [
        ('Europe/Guernsey', 'Guernsey'),
    ]),
    ('Guinea', [
        ('Africa/Conakry', 'Conakry'),
    ]),
    ('Guinea-Bissau', [
        ('Africa/Bissau', 'Bissau'),
    ]),
    ('Guyana', [
        ('America/Guyana', 'Guyana'),
    ]),
    ('Haiti', [
        ('America/Port-au-Prince', 'Port-au-Prince'),
    ]),
    ('Honduras', [
        ('America/Tegucigalpa', 'Tegucigalpa'),
    ]),
    ('Hong Kong', [
        ('Asia/Hong_Kong', 'Hong Kong'),
    ]),
    ('Hungary', [
        ('Europe/Budapest', 'Budapest'),
    ]),
    ('Iceland', [
        ('Atlantic/Reykjavik', 'Reykjavik'),
    ]),
    ('India', [
        ('Asia/Kolkata', 'Kolkata'),
    ]),
    ('Indonesia', [
        ('Asia/Jakarta', 'Jakarta'),
        ('Asia/Jayapura', 'Jayapura'),
        ('Asia/Makassar', 'Makassar'),
        ('Asia/Pontianak', 'Pontianak'),
    ]),
    ('Iran', [
        ('Asia/Tehran', 'Tehran'),
    ]),
    ('Iraq', [
        ('Asia/Baghdad', 'Baghdad'),
    ]),
    ('Isle of Man', [
        ('Europe/Isle_of_Man', 'Isle of Man'),
    ]),
    ('Israel', [
        ('Asia/Jerusalem', 'Jerusalem'),
    ]),
    ('Italy', [
        ('Europe/Rome', 'Rome'),
    ]),
    ('Jamaica', [
        ('America/Jamaica', 'Jamaica'),
    ]),
    ('Japan', [
        ('Asia/Tokyo', 'Tokyo'),
    ]),
    ('Jersey', [
        ('Europe/Jersey', 'Jersey'),
    ]),
    ('Jordan', [
        ('Asia/Amman', 'Amman'),
    ]),
    ('Kazakhstan', [
        ('Asia/Almaty', 'Almaty'),
        ('Asia/Aqtau', 'Aqtau'),
        ('Asia/Aqtobe', 'Aqtobe'),
        ('Asia/Atyrau', 'Atyrau'),
        ('Asia/Oral', 'Oral'),
        ('Asia/Qostanay', 'Qostanay'),
        ('Asia/Qyzylorda', 'Qyzylorda'),
    ]),
    ('Kenya', [
        ('Africa/Nairobi', 'Nairobi'),
    ]),
    ('Kiribati', [
        ('Pacific/Kanton', 'Kanton'),
        ('Pacific/Kiritimati', 'Kiritimati'),
        ('Pacific/Tarawa', 'Tarawa'),
    ]),
    ('Korea (North)', [
        ('Asia/Pyongyang', 'Pyongyang'),
    ]),
    ('Korea (South)', [
        ('Asia/Seoul', 'Seoul'),
    ]),
    ('Kuwait', [
        ('Asia/Kuwait', 'Kuwait'),
    ]),
    ('Kyrgyzstan', [
        ('Asia/Bishkek', 'Bishkek'),
    ]),
    ('Laos', [
        ('Asia/Vientiane', 'Vientiane'),
    ]),
    ('Latvia', [
        ('Europe/Riga', 'Riga'),
    ]),
    ('Lebanon', [
        ('Asia/Beirut', 'Beirut'),
    ]),
    ('Lesotho', [
        ('Africa/Maseru', 'Maseru'),
    ]),
    ('Liberia', [
        ('Africa/Monrovia', 'Monrovia'),
    ]),
    ('Libya', [
        ('Africa/Tripoli', 'Tripoli'),
    ]),
    ('Liechtenstein', [
        ('Europe/Vaduz', 'Vaduz'),
    ]),
    ('Lithuania', [
        ('Europe/Vilnius', 'Vilnius'),
    ]),
    ('Luxembourg', [
        ('Europe/Luxembourg', 'Luxembourg'),
    ]),
    ('Macau', [
        ('Asia/Macau', 'Macau'),
    ]),
    ('Madagascar', [
        ('Indian/Antananarivo', 'Antananarivo'),
    ]),
    ('Malawi', [
        ('Africa/Blantyre', 'Blantyre'),
    ]),
    ('Malaysia', [
        ('Asia/Kuala_Lumpur', 'Kuala Lumpur'),
        ('Asia/Kuching', 'Kuching'),
    ]),
    ('Maldives', [
        ('Indian/Maldives', 'Maldives'),
    ]),
    ('Mali', [
        ('Africa/Bamako', 'Bamako'),
    ]),
    ('Malta', [
        ('Europe/Malta', 'Malta'),
    ]),
    ('Marshall Islands', [
        ('Pacific/Kwajalein', 'Kwajalein'),
        ('Pacific/Majuro', 'Majuro'),
    ]),
    ('Martinique', [
        ('America/Martinique', 'Martinique'),
    ]),
    ('Mauritania', [
        ('Africa/Nouakchott', 'Nouakchott'),
    ]),
    ('Mauritius', [
        ('Indian/Mauritius', 'Mauritius'),
    ]),
    ('Mayotte', [
        ('Indian/Mayotte', 'Mayotte'),
    ]),
    ('Mexico', [
        ('America/Bahia_Banderas', 'Bahia Banderas'),
        ('America/Cancun', 'Cancun'),
        ('America/Chihuahua', 'Chihuahua'),
        ('America/Ciudad_Juarez', 'Ciudad Juarez'),
        ('America/Hermosillo', 'Hermosillo'),
        ('America/Matamoros', 'Matamoros'),
        ('America/Mazatlan', 'Mazatlan'),
        ('America/Merida', 'Merida'),
        ('America/Mexico_City', 'Mexico City'),
        ('America/Monterrey', 'Monterrey'),
        ('America/Ojinaga', 'Ojinaga'),
        ('America/Tijuana', 'Tijuana'),
    ]),
    ('Micronesia', [
        ('Pacific/Chuuk', 'Chuuk'),
        ('Pacific/Kosrae', 'Kosrae'),
        ('Pacific/Pohnpei', 'Pohnpei'),
    ]),
    ('Moldova', [
        ('Europe/Chisinau', 'Chisinau'),
    ]),
    ('Monaco', [
        ('Europe/Monaco', 'Monaco'),
    ]),
    ('Mongolia', [
        ('Asia/Hovd', 'Hovd'),
        ('Asia/Ulaanbaatar', 'Ulaanbaatar'),
    ]),
    ('Montenegro', [
        ('Europe/Podgorica', 'Podgorica'),
    ]),
    ('Montserrat', [
        ('America/Montserrat', 'Montserrat'),
    ]),
    ('Morocco', [
        ('Africa/Casablanca', 'Casablanca'),
    ]),
    ('Mozambique', [
        ('Africa/Maputo', 'Maputo'),
    ]),
    ('Myanmar (Burma)', [
        ('Asia/Yangon', 'Yangon'),
    ]),
    ('Namibia', [
        ('Africa/Windhoek', 'Windhoek'),
    ]),
    ('Nauru', [
        ('Pacific/Nauru', 'Nauru'),
    ]),
    ('Nepal', [
        ('Asia/Kathmandu', 'Kathmandu'),
    ]),
    ('Netherlands', [
        ('Europe/Amsterdam', 'Amsterdam'),
    ]),
    ('New Caledonia', [
        ('Pacific/Noumea', 'Noumea'),
    ]),
    ('Nicaragua', [
        ('America/Managua', 'Managua'),
    ]),
    ('Niger', [
        ('Africa/Niamey', 'Niamey'),
    ]),
    ('Nigeria', [
        ('Africa/Lagos', 'Lagos'),
    ]),
    ('Niue', [
        ('Pacific/Niue', 'Niue'),
    ]),
    ('Norfolk Island', [
        ('Pacific/Norfolk', 'Norfolk'),
    ]),
    ('North Macedonia', [
        ('Europe/Skopje', 'Skopje'),
    ]),
    ('Northern Mariana Islands', [
        ('Pacific/Saipan', 'Saipan'),
    ]),
    ('Norway', [
        ('Europe/Oslo', 'Oslo'),
    ]),
    ('Oman', [
        ('Asia/Muscat', 'Muscat'),
    ]),
    ('Pakistan', [
        ('Asia/Karachi', 'Karachi'),
    ]),
    ('Palau', [
        ('Pacific/Palau', 'Palau'),
    ]),
    ('Palestine', [
        ('Asia/Gaza', 'Gaza'),
        ('Asia/Hebron', 'Hebron'),
    ]),
    ('Panama', [
        ('America/Panama', 'Panama'),
    ]),
    ('Papua New Guinea', [
        ('Pacific/Bougainville', 'Bougainville'),
        ('Pacific/Port_Moresby', 'Port Moresby'),
    ]),
    ('Paraguay', [
        ('America/Asuncion', 'Asuncion'),
    ]),
    ('Peru', [
        ('America/Lima', 'Lima'),
    ]),
    ('Philippines', [
        ('Asia/Manila', 'Manila'),
    ]),
    ('Pitcairn', [
        ('Pacific/Pitcairn', 'Pitcairn'),
    ]),
    ('Poland', [
        ('Europe/Warsaw', 'Warsaw'),
    ]),
    ('Portugal', [
        ('Atlantic/Azores', 'Azores'),
        ('Europe/Lisbon', 'Lisbon'),
        ('Atlantic/Madeira', 'Madeira'),
    ]),
    ('Puerto Rico', [
        ('America/Puerto_Rico', 'Puerto Rico'),
    ]),
    ('Qatar', [
        ('Asia/Qatar', 'Qatar'),
    ]),
    ('Romania', [
        ('Europe/Bucharest', 'Bucharest'),
    ]),
    ('Russia', [
        ('Asia/Anadyr', 'Anadyr'),
        ('Europe/Astrakhan', 'Astrakhan'),
        ('Asia/Barnaul', 'Barnaul'),
        ('Asia/Chita', 'Chita'),
        ('Asia/Irkutsk', 'Irkutsk'),
        ('Europe/Kaliningrad', 'Kaliningrad'),
        ('Asia/Kamchatka', 'Kamchatka'),
        ('Asia/Khandyga', 'Khandyga'),
        ('Europe/Kirov', 'Kirov'),
        ('Asia/Krasnoyarsk', 'Krasnoyarsk'),
        ('Asia/Magadan', 'Magadan'),
        ('Europe/Moscow', 'Moscow'),
        ('Asia/Novokuznetsk', 'Novokuznetsk'),
        ('Asia/Novosibirsk', 'Novosibirsk'),
        ('Asia/Omsk', 'Omsk'),
        ('Asia/Sakhalin', 'Sakhalin'),
        ('Europe/Samara', 'Samara'),
        ('Europe/Saratov', 'Saratov'),
        ('Asia/Srednekolymsk', 'Srednekolymsk'),
        ('Asia/Tomsk', 'Tomsk'),
        ('Europe/Ulyanovsk', 'Ulyanovsk'),
        ('Asia/Ust-Nera', 'Ust-Nera'),
        ('Asia/Vladivostok', 'Vladivostok'),
        ('Europe/Volgograd', 'Volgograd'),
        ('Asia/Yakutsk', 'Yakutsk'),
        ('Asia/Yekaterinburg', 'Yekaterinburg'),
    ]),
    ('Rwanda', [
        ('Africa/Kigali', 'Kigali'),
    ]),
    ('Réunion', [
        ('Indian/Reunion', 'Reunion'),
    ]),
    ('Samoa (American)', [
        ('Pacific/Pago_Pago', 'Pago Pago'),
    ]),
    ('Samoa (western)', [
        ('Pacific/Apia', 'Apia'),
    ]),
    ('San Marino', [
        ('Europe/San_Marino', 'San Marino'),
    ]),
    ('Sao Tome & Principe', [
        ('Africa/Sao_Tome', 'Sao Tome'),
    ]),
    ('Saudi Arabia', [
        ('Asia/Riyadh', 'Riyadh'),
    ]),
    ('Senegal', [
        ('Africa/Dakar', 'Dakar'),
    ]),
    ('Serbia', [
        ('Europe/Belgrade', 'Belgrade'),
    ]),
    ('Seychelles', [
        ('Indian/Mahe', 'Mahe'),
    ]),
    ('Sierra Leone', [
        ('Africa/Freetown', 'Freetown'),
    ]),
    ('Singapore', [
        ('Asia/Singapore', 'Singapore'),
    ]),
    ('Slovakia', [
        ('Europe/Bratislava', 'Bratislava'),
    ]),
    ('Slovenia', [
        ('Europe/Ljubljana', 'Ljubljana'),
    ]),
    ('Solomon Islands', [
        ('Pacific/Guadalcanal', 'Guadalcanal'),
    ]),
    ('Somalia', [
        ('Africa/Mogadishu', 'Mogadishu'),
    ]),
    ('South Africa', [
        ('Africa/Johannesburg', 'Johannesburg'),
    ]),
    ('South Georgia & the South Sandwich Islands', [
        ('Atlantic/South_Georgia', 'South Georgia'),
    ]),
    ('South Sudan', [
        ('Africa/Juba', 'Juba'),
    ]),
    ('Spain', [
        ('Atlantic/Canary', 'Canary'),
        ('Africa/Ceuta', 'Ceuta'),
        ('Europe/Madrid', 'Madrid'),
    ]),
    ('Sri Lanka', [
        ('Asia/Colombo', 'Colombo'),
    ]),
    ('St Barthelemy', [
        ('America/St_Barthelemy', 'St Barthelemy'),
    ]),
    ('St Helena', [
        ('Atlantic/St_Helena', 'St Helena'),
    ]),
    ('St Kitts & Nevis', [
        ('America/St_Kitts', 'St Kitts'),
    ]),
    ('St Lucia', [
        ('America/St_Lucia', 'St Lucia'),
    ]),
    ('St Maarten (Dutch)', [
        ('America/Lower_Princes', 'Lower Princes'),
    ]),
    ('St Martin (French)', [
        ('America/Marigot', 'Marigot'),
    ]),
    ('St Pierre & Miquelon', [
        ('America/Miquelon', 'Miquelon'),
    ]),
    ('St Vincent', [
        ('America/St_Vincent', 'St Vincent'),
    ]),
    ('Sudan', [
        ('Africa/Khartoum', 'Khartoum'),
    ]),
    ('Suriname', [
        ('America/Paramaribo', 'Paramaribo'),
    ]),
    ('Svalbard & Jan Mayen', [
        ('Arctic/Longyearbyen', 'Longyearbyen'),
    ]),
    ('Sweden', [
        ('Europe/Stockholm', 'Stockholm'),
    ]),
    ('Switzerland', [
        ('Europe/Zurich', 'Zurich'),
    ]),
    ('Syria', [
        ('Asia/Damascus', 'Damascus'),
    ]),
    ('Taiwan', [
        ('Asia/Taipei', 'Taipei'),
    ]),
    ('Tajikistan', [
        ('Asia/Dushanbe', 'Dushanbe'),
    ]),
    ('Tanzania', [
        ('Africa/Dar_es_Salaam', 'Dar es Salaam'),
    ]),
    ('Thailand', [
        ('Asia/Bangkok', 'Bangkok'),
    ]),
    ('Togo', [
        ('Africa/Lome', 'Lome'),
    ]),
    ('Tokelau', [
        ('Pacific/Fakaofo', 'Fakaofo'),
    ]),
    ('Tonga', [
        ('Pacific/Tongatapu', 'Tongatapu'),
    ]),
    ('Trinidad & Tobago', [
        ('America/Port_of_Spain', 'Port of Spain'),
    ]),
    ('Tunisia', [
        ('Africa/Tunis', 'Tunis'),
    ]),
    ('Turkey', [
        ('Europe/Istanbul', 'Istanbul'),
    ]),
    ('Turkmenistan', [
        ('Asia/Ashgabat', 'Ashgabat'),
    ]),
    ('Turks & Caicos Is', [
        ('America/Grand_Turk', 'Grand Turk'),
    ]),
    ('Tuvalu', [
        ('Pacific/Funafuti', 'Funafuti'),
    ]),
    ('Uganda', [
        ('Africa/Kampala', 'Kampala'),
    ]),
    ('Ukraine', [
        ('Europe/Kyiv', 'Kyiv'),
        ('Europe/Simferopol', 'Simferopol'),
    ]),
    ('United Arab Emirates', [
        ('Asia/Dubai', 'Dubai'),
    ]),
    ('Uruguay', [
        ('America/Montevideo', 'Montevideo'),
    ]),
    ('US minor outlying islands', [
        ('Pacific/Midway', 'Midway'),
        ('Pacific/Wake', 'Wake'),
    ]),
    ('Uzbekistan', [
        ('Asia/Samarkand', 'Samarkand'),
        ('Asia/Tashkent', 'Tashkent'),
    ]),
    ('Vanuatu', [
        ('Pacific/Efate', 'Efate'),
    ]),
    ('Vatican City', [
        ('Europe/Vatican', 'Vatican'),
    ]),
    ('Venezuela', [
        ('America/Caracas', 'Caracas'),
    ]),
    ('Vietnam', [
        ('Asia/Ho_Chi_Minh', 'Ho Chi Minh'),
    ]),
    ('Virgin Islands (UK)', [
        ('America/Tortola', 'Tortola'),
    ]),
    ('Virgin Islands (US)', [
        ('America/St_Thomas', 'St Thomas'),
    ]),
    ('Wallis & Futuna', [
        ('Pacific/Wallis', 'Wallis'),
    ]),
    ('Western Sahara', [
        ('Africa/El_Aaiun', 'El Aaiun'),
    ]),
    ('Yemen', [
        ('Asia/Aden', 'Aden'),
    ]),
    ('Zambia', [
        ('Africa/Lusaka', 'Lusaka'),
    ]),
    ('Zimbabwe', [
        ('Africa/Harare', 'Harare'),
    ]),
    ('Åland Islands', [
        ('Europe/Mariehamn', 'Mariehamn'),
    ]),
]
